### Create credit
POST {{credit.url}}/credit
Content-Type: application/json
X-Authorized-Id: {{credit.operator}}

{
  "user_id": "{{user_id}}",
  "percent": 24,
  "balance": 1200000000,
  "type": "SIMPLE"
}

### Create credit
POST {{credit.url}}/credit
Content-Type: application/json
X-Authorized-Id: {{credit.operator}}

{
  "user_id": "{{user_id}}",
  "percent": 24,
  "balance": 1200000,
  "type": "MICRO"
}