CREATE DATABASE keycloak WITH ENCODING = "UTF-8";
\c keycloak;
CREATE SCHEMA keycloak;


CREATE DATABASE wish WITH ENCODING = "UTF-8";
\c wish;
CREATE SCHEMA wallet;
CREATE SCHEMA credit;
CREATE SCHEMA account;
CREATE SCHEMA users;
CREATE SCHEMA notify;
CREATE SCHEMA wishlist;
