//edition = "2023";

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: middleware/wallet.proto

package wallet

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WalletType int32

const (
	WalletType_UNKNOWN_TYPE WalletType = 0
	WalletType_USER         WalletType = 1
	WalletType_COMMON       WalletType = 2
)

// Enum value maps for WalletType.
var (
	WalletType_name = map[int32]string{
		0: "UNKNOWN_TYPE",
		1: "USER",
		2: "COMMON",
	}
	WalletType_value = map[string]int32{
		"UNKNOWN_TYPE": 0,
		"USER":         1,
		"COMMON":       2,
	}
)

func (x WalletType) Enum() *WalletType {
	p := new(WalletType)
	*p = x
	return p
}

func (x WalletType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WalletType) Descriptor() protoreflect.EnumDescriptor {
	return file_middleware_wallet_proto_enumTypes[0].Descriptor()
}

func (WalletType) Type() protoreflect.EnumType {
	return &file_middleware_wallet_proto_enumTypes[0]
}

func (x WalletType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WalletType.Descriptor instead.
func (WalletType) EnumDescriptor() ([]byte, []int) {
	return file_middleware_wallet_proto_rawDescGZIP(), []int{0}
}

type WalletState int32

const (
	WalletState_UNKNOWN_STATE WalletState = 0
	WalletState_ACTIVE        WalletState = 1
	WalletState_BLOCKED       WalletState = 2
	WalletState_DELETED       WalletState = 3
	WalletState_CLOSED        WalletState = 4
)

// Enum value maps for WalletState.
var (
	WalletState_name = map[int32]string{
		0: "UNKNOWN_STATE",
		1: "ACTIVE",
		2: "BLOCKED",
		3: "DELETED",
		4: "CLOSED",
	}
	WalletState_value = map[string]int32{
		"UNKNOWN_STATE": 0,
		"ACTIVE":        1,
		"BLOCKED":       2,
		"DELETED":       3,
		"CLOSED":        4,
	}
)

func (x WalletState) Enum() *WalletState {
	p := new(WalletState)
	*p = x
	return p
}

func (x WalletState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WalletState) Descriptor() protoreflect.EnumDescriptor {
	return file_middleware_wallet_proto_enumTypes[1].Descriptor()
}

func (WalletState) Type() protoreflect.EnumType {
	return &file_middleware_wallet_proto_enumTypes[1]
}

func (x WalletState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WalletState.Descriptor instead.
func (WalletState) EnumDescriptor() ([]byte, []int) {
	return file_middleware_wallet_proto_rawDescGZIP(), []int{1}
}

type InformationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        *string                `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3,oneof" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InformationRequest) Reset() {
	*x = InformationRequest{}
	mi := &file_middleware_wallet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InformationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InformationRequest) ProtoMessage() {}

func (x *InformationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_middleware_wallet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InformationRequest.ProtoReflect.Descriptor instead.
func (*InformationRequest) Descriptor() ([]byte, []int) {
	return file_middleware_wallet_proto_rawDescGZIP(), []int{0}
}

func (x *InformationRequest) GetUserId() string {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return ""
}

type InformationReply struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Balance        int64                  `protobuf:"varint,2,opt,name=balance,proto3" json:"balance,omitempty"`
	ReservedDebit  int64                  `protobuf:"varint,3,opt,name=reserved_debit,json=reservedDebit,proto3" json:"reserved_debit,omitempty"`
	ReservedCredit int64                  `protobuf:"varint,4,opt,name=reserved_credit,json=reservedCredit,proto3" json:"reserved_credit,omitempty"`
	Type           WalletType             `protobuf:"varint,14,opt,name=type,proto3,enum=wallet.WalletType" json:"type,omitempty"`
	State          WalletState            `protobuf:"varint,15,opt,name=state,proto3,enum=wallet.WalletState" json:"state,omitempty"`
	Transactions   int64                  `protobuf:"varint,16,opt,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InformationReply) Reset() {
	*x = InformationReply{}
	mi := &file_middleware_wallet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InformationReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InformationReply) ProtoMessage() {}

func (x *InformationReply) ProtoReflect() protoreflect.Message {
	mi := &file_middleware_wallet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InformationReply.ProtoReflect.Descriptor instead.
func (*InformationReply) Descriptor() ([]byte, []int) {
	return file_middleware_wallet_proto_rawDescGZIP(), []int{1}
}

func (x *InformationReply) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InformationReply) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *InformationReply) GetReservedDebit() int64 {
	if x != nil {
		return x.ReservedDebit
	}
	return 0
}

func (x *InformationReply) GetReservedCredit() int64 {
	if x != nil {
		return x.ReservedCredit
	}
	return 0
}

func (x *InformationReply) GetType() WalletType {
	if x != nil {
		return x.Type
	}
	return WalletType_UNKNOWN_TYPE
}

func (x *InformationReply) GetState() WalletState {
	if x != nil {
		return x.State
	}
	return WalletState_UNKNOWN_STATE
}

func (x *InformationReply) GetTransactions() int64 {
	if x != nil {
		return x.Transactions
	}
	return 0
}

type InformationReplyList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Replies       []*InformationReply    `protobuf:"bytes,1,rep,name=replies,proto3" json:"replies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InformationReplyList) Reset() {
	*x = InformationReplyList{}
	mi := &file_middleware_wallet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InformationReplyList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InformationReplyList) ProtoMessage() {}

func (x *InformationReplyList) ProtoReflect() protoreflect.Message {
	mi := &file_middleware_wallet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InformationReplyList.ProtoReflect.Descriptor instead.
func (*InformationReplyList) Descriptor() ([]byte, []int) {
	return file_middleware_wallet_proto_rawDescGZIP(), []int{2}
}

func (x *InformationReplyList) GetReplies() []*InformationReply {
	if x != nil {
		return x.Replies
	}
	return nil
}

var File_middleware_wallet_proto protoreflect.FileDescriptor

const file_middleware_wallet_proto_rawDesc = "" +
	"\n" +
	"\x17middleware/wallet.proto\x12\x06wallet\">\n" +
	"\x12InformationRequest\x12\x1c\n" +
	"\auser_id\x18\x01 \x01(\tH\x00R\x06userId\x88\x01\x01B\n" +
	"\n" +
	"\b_user_id\"\xb9\x02\n" +
	"\x10InformationReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\abalance\x18\x02 \x01(\x03R\abalance\x12%\n" +
	"\x0ereserved_debit\x18\x03 \x01(\x03R\rreservedDebit\x12'\n" +
	"\x0freserved_credit\x18\x04 \x01(\x03R\x0ereservedCredit\x12&\n" +
	"\x04type\x18\x0e \x01(\x0e2\x12.wallet.WalletTypeR\x04type\x12)\n" +
	"\x05state\x18\x0f \x01(\x0e2\x13.wallet.WalletStateR\x05state\x12\"\n" +
	"\ftransactions\x18\x10 \x01(\x03R\ftransactionsJ\x04\b\x05\x10\x06J\x04\b\x06\x10\aJ\x04\b\a\x10\bJ\x04\b\b\x10\tJ\x04\b\t\x10\n" +
	"J\x04\b\n" +
	"\x10\vJ\x04\b\v\x10\fJ\x04\b\f\x10\rJ\x04\b\r\x10\x0e\"J\n" +
	"\x14InformationReplyList\x122\n" +
	"\areplies\x18\x01 \x03(\v2\x18.wallet.InformationReplyR\areplies*4\n" +
	"\n" +
	"WalletType\x12\x10\n" +
	"\fUNKNOWN_TYPE\x10\x00\x12\b\n" +
	"\x04USER\x10\x01\x12\n" +
	"\n" +
	"\x06COMMON\x10\x02*R\n" +
	"\vWalletState\x12\x11\n" +
	"\rUNKNOWN_STATE\x10\x00\x12\n" +
	"\n" +
	"\x06ACTIVE\x10\x01\x12\v\n" +
	"\aBLOCKED\x10\x02\x12\v\n" +
	"\aDELETED\x10\x03\x12\n" +
	"\n" +
	"\x06CLOSED\x10\x042R\n" +
	"\aService\x12G\n" +
	"\vInformation\x12\x1a.wallet.InformationRequest\x1a\x1c.wallet.InformationReplyListB\x13Z\x11middleware/walletb\x06proto3"

var (
	file_middleware_wallet_proto_rawDescOnce sync.Once
	file_middleware_wallet_proto_rawDescData []byte
)

func file_middleware_wallet_proto_rawDescGZIP() []byte {
	file_middleware_wallet_proto_rawDescOnce.Do(func() {
		file_middleware_wallet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_middleware_wallet_proto_rawDesc), len(file_middleware_wallet_proto_rawDesc)))
	})
	return file_middleware_wallet_proto_rawDescData
}

var file_middleware_wallet_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_middleware_wallet_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_middleware_wallet_proto_goTypes = []any{
	(WalletType)(0),              // 0: wallet.WalletType
	(WalletState)(0),             // 1: wallet.WalletState
	(*InformationRequest)(nil),   // 2: wallet.InformationRequest
	(*InformationReply)(nil),     // 3: wallet.InformationReply
	(*InformationReplyList)(nil), // 4: wallet.InformationReplyList
}
var file_middleware_wallet_proto_depIdxs = []int32{
	0, // 0: wallet.InformationReply.type:type_name -> wallet.WalletType
	1, // 1: wallet.InformationReply.state:type_name -> wallet.WalletState
	3, // 2: wallet.InformationReplyList.replies:type_name -> wallet.InformationReply
	2, // 3: wallet.Service.Information:input_type -> wallet.InformationRequest
	4, // 4: wallet.Service.Information:output_type -> wallet.InformationReplyList
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_middleware_wallet_proto_init() }
func file_middleware_wallet_proto_init() {
	if File_middleware_wallet_proto != nil {
		return
	}
	file_middleware_wallet_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_middleware_wallet_proto_rawDesc), len(file_middleware_wallet_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_middleware_wallet_proto_goTypes,
		DependencyIndexes: file_middleware_wallet_proto_depIdxs,
		EnumInfos:         file_middleware_wallet_proto_enumTypes,
		MessageInfos:      file_middleware_wallet_proto_msgTypes,
	}.Build()
	File_middleware_wallet_proto = out.File
	file_middleware_wallet_proto_goTypes = nil
	file_middleware_wallet_proto_depIdxs = nil
}
