filebeat.inputs:
- type: filestream
  enabled: true
  paths:
    - /logs/credit/*.log
  fields:
    service: "credit"

- type: filestream
  enabled: true
  paths:
    - /logs/wallet/*.log
  fields:
    service: "wallet"
- type: filestream
  enabled: true
  paths:
    - /logs/users/*.log
  fields:
    service: "users"

output.logstash:
  hosts: ["logstash:5044"]