//edition = "2023";
syntax = "proto3";

option go_package = "middleware/wallet";

package wallet;

enum WalletType {
  USER = 0;
  COMMON = 1;
}

enum WalletState {
  ACTIVE = 0;
  BLOCKED = 1;
  DELETED = 2;
  CLOSED = 3;
}

message InformationRequest {
  string user_id = 1;
}

message InformationReply {
  string id = 1;
  int64 balance = 2;
  int64 reserved_debit = 3;
  int64 reserved_credit = 4;
  reserved 10;
  WalletType type = 14;
  WalletState state = 15;
  int64 transactions = 16;
}

service Service {
  rpc Information(InformationRequest) returns (stream InformationReply);
}