//edition = "2023";
syntax = "proto3";

option go_package = "middleware/wallet";

package wallet;

enum WalletType {
  UNKNOWN_TYPE = 0;
  USER = 1;
  COMMON = 2;
}

enum WalletState {
  UNKNOWN_STATE = 0;
  ACTIVE = 1;
  BLOCKED = 2;
  DELETED = 3;
  CLOSED = 4;
}

message InformationRequest {
  optional string user_id = 1;
}

message InformationReply {
  string id = 1;
  int64 balance = 2;
  int64 reserved_debit = 3;
  int64 reserved_credit = 4;
  reserved 5, 6, 7, 8, 9, 10, 11, 12, 13;
  WalletType type = 14;
  WalletState state = 15;
  int64 transactions = 16;
}

message InformationReplyList {
  repeated InformationReply replies = 1;
}

service Service {
  rpc Information(InformationRequest) returns (InformationReplyList);
}