ALTER TABLE users
    ALTER COLUMN created_at TYPE TIMESTAMPTZ;
ALTER TABLE oauth_clients
    ALTER COLUMN created_at TYPE TIMESTAMPTZ;
ALTER TABLE keys
    ALTER COLUMN created_at TYPE TIMESTAMPTZ;
ALTER TABLE oauth_tokens
    ALTER COLUMN expires_at TYPE TIMESTAMPTZ,
    ALTER COLUMN created_at TYPE TIMESTAMPTZ;
ALTER TABLE user_roles
    ALTER COLUMN created_at TYPE TIMESTAMPTZ;
