// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.36.0
// source: middleware/wallet.proto

// Версия в имени пакета: путь метода включает его, поэтому несовместимое
// изменение контракта означает новую версию, а не молчаливую поломку клиентов.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Service_Information_FullMethodName = "/wallet.v1.Service/Information"
	Service_Debit_FullMethodName       = "/wallet.v1.Service/Debit"
	Service_Credit_FullMethodName      = "/wallet.v1.Service/Credit"
	Service_Transfer_FullMethodName    = "/wallet.v1.Service/Transfer"
	Service_History_FullMethodName     = "/wallet.v1.Service/History"
	Service_ChangeState_FullMethodName = "/wallet.v1.Service/ChangeState"
	Service_Reserve_FullMethodName     = "/wallet.v1.Service/Reserve"
	Service_Confirm_FullMethodName     = "/wallet.v1.Service/Confirm"
	Service_Reject_FullMethodName      = "/wallet.v1.Service/Reject"
)

// ServiceClient is the client API for Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServiceClient interface {
	Information(ctx context.Context, in *InformationRequest, opts ...grpc.CallOption) (*InformationReplyList, error)
	// Зачисление средств на кошелёк.
	Debit(ctx context.Context, in *OperationRequest, opts ...grpc.CallOption) (*TransactionReply, error)
	// Списание средств с кошелька.
	Credit(ctx context.Context, in *OperationRequest, opts ...grpc.CallOption) (*TransactionReply, error)
	// Перевод между кошельками.
	Transfer(ctx context.Context, in *TransferRequest, opts ...grpc.CallOption) (*TransactionReply, error)
	// История операций с постраничной выдачей.
	History(ctx context.Context, in *HistoryRequest, opts ...grpc.CallOption) (*HistoryReply, error)
	// Смена состояния кошелька.
	ChangeState(ctx context.Context, in *ChangeStateRequest, opts ...grpc.CallOption) (*InformationReply, error)
	// Резервирование средств под будущее списание.
	Reserve(ctx context.Context, in *ReserveRequest, opts ...grpc.CallOption) (*TransactionReply, error)
	// Подтверждение резерва: средства списываются.
	Confirm(ctx context.Context, in *SettleRequest, opts ...grpc.CallOption) (*TransactionReply, error)
	// Отмена резерва: средства освобождаются.
	Reject(ctx context.Context, in *SettleRequest, opts ...grpc.CallOption) (*TransactionReply, error)
}

type serviceClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceClient(cc grpc.ClientConnInterface) ServiceClient {
	return &serviceClient{cc}
}

func (c *serviceClient) Information(ctx context.Context, in *InformationRequest, opts ...grpc.CallOption) (*InformationReplyList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InformationReplyList)
	err := c.cc.Invoke(ctx, Service_Information_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) Debit(ctx context.Context, in *OperationRequest, opts ...grpc.CallOption) (*TransactionReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransactionReply)
	err := c.cc.Invoke(ctx, Service_Debit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) Credit(ctx context.Context, in *OperationRequest, opts ...grpc.CallOption) (*TransactionReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransactionReply)
	err := c.cc.Invoke(ctx, Service_Credit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) Transfer(ctx context.Context, in *TransferRequest, opts ...grpc.CallOption) (*TransactionReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransactionReply)
	err := c.cc.Invoke(ctx, Service_Transfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) History(ctx context.Context, in *HistoryRequest, opts ...grpc.CallOption) (*HistoryReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HistoryReply)
	err := c.cc.Invoke(ctx, Service_History_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) ChangeState(ctx context.Context, in *ChangeStateRequest, opts ...grpc.CallOption) (*InformationReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InformationReply)
	err := c.cc.Invoke(ctx, Service_ChangeState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) Reserve(ctx context.Context, in *ReserveRequest, opts ...grpc.CallOption) (*TransactionReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransactionReply)
	err := c.cc.Invoke(ctx, Service_Reserve_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) Confirm(ctx context.Context, in *SettleRequest, opts ...grpc.CallOption) (*TransactionReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransactionReply)
	err := c.cc.Invoke(ctx, Service_Confirm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) Reject(ctx context.Context, in *SettleRequest, opts ...grpc.CallOption) (*TransactionReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransactionReply)
	err := c.cc.Invoke(ctx, Service_Reject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceServer is the server API for Service service.
// All implementations must embed UnimplementedServiceServer
// for forward compatibility.
type ServiceServer interface {
	Information(context.Context, *InformationRequest) (*InformationReplyList, error)
	// Зачисление средств на кошелёк.
	Debit(context.Context, *OperationRequest) (*TransactionReply, error)
	// Списание средств с кошелька.
	Credit(context.Context, *OperationRequest) (*TransactionReply, error)
	// Перевод между кошельками.
	Transfer(context.Context, *TransferRequest) (*TransactionReply, error)
	// История операций с постраничной выдачей.
	History(context.Context, *HistoryRequest) (*HistoryReply, error)
	// Смена состояния кошелька.
	ChangeState(context.Context, *ChangeStateRequest) (*InformationReply, error)
	// Резервирование средств под будущее списание.
	Reserve(context.Context, *ReserveRequest) (*TransactionReply, error)
	// Подтверждение резерва: средства списываются.
	Confirm(context.Context, *SettleRequest) (*TransactionReply, error)
	// Отмена резерва: средства освобождаются.
	Reject(context.Context, *SettleRequest) (*TransactionReply, error)
	mustEmbedUnimplementedServiceServer()
}

// UnimplementedServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedServiceServer struct{}

func (UnimplementedServiceServer) Information(context.Context, *InformationRequest) (*InformationReplyList, error) {
	return nil, status.Error(codes.Unimplemented, "method Information not implemented")
}
func (UnimplementedServiceServer) Debit(context.Context, *OperationRequest) (*TransactionReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Debit not implemented")
}
func (UnimplementedServiceServer) Credit(context.Context, *OperationRequest) (*TransactionReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Credit not implemented")
}
func (UnimplementedServiceServer) Transfer(context.Context, *TransferRequest) (*TransactionReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Transfer not implemented")
}
func (UnimplementedServiceServer) History(context.Context, *HistoryRequest) (*HistoryReply, error) {
	return nil, status.Error(codes.Unimplemented, "method History not implemented")
}
func (UnimplementedServiceServer) ChangeState(context.Context, *ChangeStateRequest) (*InformationReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ChangeState not implemented")
}
func (UnimplementedServiceServer) Reserve(context.Context, *ReserveRequest) (*TransactionReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Reserve not implemented")
}
func (UnimplementedServiceServer) Confirm(context.Context, *SettleRequest) (*TransactionReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Confirm not implemented")
}
func (UnimplementedServiceServer) Reject(context.Context, *SettleRequest) (*TransactionReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Reject not implemented")
}
func (UnimplementedServiceServer) mustEmbedUnimplementedServiceServer() {}
func (UnimplementedServiceServer) testEmbeddedByValue()                 {}

// UnsafeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceServer will
// result in compilation errors.
type UnsafeServiceServer interface {
	mustEmbedUnimplementedServiceServer()
}

func RegisterServiceServer(s grpc.ServiceRegistrar, srv ServiceServer) {
	// If the following call panics, it indicates UnimplementedServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Service_ServiceDesc, srv)
}

func _Service_Information_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InformationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).Information(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_Information_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).Information(ctx, req.(*InformationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_Debit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).Debit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_Debit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).Debit(ctx, req.(*OperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_Credit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).Credit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_Credit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).Credit(ctx, req.(*OperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_Transfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).Transfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_Transfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).Transfer(ctx, req.(*TransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_History_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).History(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_History_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).History(ctx, req.(*HistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_ChangeState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).ChangeState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_ChangeState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).ChangeState(ctx, req.(*ChangeStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_Reserve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReserveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).Reserve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_Reserve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).Reserve(ctx, req.(*ReserveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_Confirm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).Confirm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_Confirm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).Confirm(ctx, req.(*SettleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_Reject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).Reject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_Reject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).Reject(ctx, req.(*SettleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Service_ServiceDesc is the grpc.ServiceDesc for Service service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Service_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wallet.v1.Service",
	HandlerType: (*ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Information",
			Handler:    _Service_Information_Handler,
		},
		{
			MethodName: "Debit",
			Handler:    _Service_Debit_Handler,
		},
		{
			MethodName: "Credit",
			Handler:    _Service_Credit_Handler,
		},
		{
			MethodName: "Transfer",
			Handler:    _Service_Transfer_Handler,
		},
		{
			MethodName: "History",
			Handler:    _Service_History_Handler,
		},
		{
			MethodName: "ChangeState",
			Handler:    _Service_ChangeState_Handler,
		},
		{
			MethodName: "Reserve",
			Handler:    _Service_Reserve_Handler,
		},
		{
			MethodName: "Confirm",
			Handler:    _Service_Confirm_Handler,
		},
		{
			MethodName: "Reject",
			Handler:    _Service_Reject_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "middleware/wallet.proto",
}
