// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.0
// source: middleware/wallet.proto

// Версия в имени пакета: путь метода включает его, поэтому несовместимое
// изменение контракта означает новую версию, а не молчаливую поломку клиентов.

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WalletType int32

const (
	WalletType_UNKNOWN_TYPE WalletType = 0
	WalletType_USER         WalletType = 1
	WalletType_COMMON       WalletType = 2
)

// Enum value maps for WalletType.
var (
	WalletType_name = map[int32]string{
		0: "UNKNOWN_TYPE",
		1: "USER",
		2: "COMMON",
	}
	WalletType_value = map[string]int32{
		"UNKNOWN_TYPE": 0,
		"USER":         1,
		"COMMON":       2,
	}
)

func (x WalletType) Enum() *WalletType {
	p := new(WalletType)
	*p = x
	return p
}

func (x WalletType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WalletType) Descriptor() protoreflect.EnumDescriptor {
	return file_middleware_wallet_proto_enumTypes[0].Descriptor()
}

func (WalletType) Type() protoreflect.EnumType {
	return &file_middleware_wallet_proto_enumTypes[0]
}

func (x WalletType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WalletType.Descriptor instead.
func (WalletType) EnumDescriptor() ([]byte, []int) {
	return file_middleware_wallet_proto_rawDescGZIP(), []int{0}
}

type WalletState int32

const (
	WalletState_UNKNOWN_STATE WalletState = 0
	WalletState_ACTIVE        WalletState = 1
	WalletState_BLOCKED       WalletState = 2
	WalletState_DELETED       WalletState = 3
	WalletState_CLOSED        WalletState = 4
)

// Enum value maps for WalletState.
var (
	WalletState_name = map[int32]string{
		0: "UNKNOWN_STATE",
		1: "ACTIVE",
		2: "BLOCKED",
		3: "DELETED",
		4: "CLOSED",
	}
	WalletState_value = map[string]int32{
		"UNKNOWN_STATE": 0,
		"ACTIVE":        1,
		"BLOCKED":       2,
		"DELETED":       3,
		"CLOSED":        4,
	}
)

func (x WalletState) Enum() *WalletState {
	p := new(WalletState)
	*p = x
	return p
}

func (x WalletState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WalletState) Descriptor() protoreflect.EnumDescriptor {
	return file_middleware_wallet_proto_enumTypes[1].Descriptor()
}

func (WalletState) Type() protoreflect.EnumType {
	return &file_middleware_wallet_proto_enumTypes[1]
}

func (x WalletState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WalletState.Descriptor instead.
func (WalletState) EnumDescriptor() ([]byte, []int) {
	return file_middleware_wallet_proto_rawDescGZIP(), []int{1}
}

type TransactionState int32

const (
	TransactionState_UNKNOWN_TRANSACTION_STATE TransactionState = 0
	TransactionState_RESERVED                  TransactionState = 1
	TransactionState_SUCCESS                   TransactionState = 2
	TransactionState_FAILURE                   TransactionState = 3
	TransactionState_REJECTED                  TransactionState = 4
)

// Enum value maps for TransactionState.
var (
	TransactionState_name = map[int32]string{
		0: "UNKNOWN_TRANSACTION_STATE",
		1: "RESERVED",
		2: "SUCCESS",
		3: "FAILURE",
		4: "REJECTED",
	}
	TransactionState_value = map[string]int32{
		"UNKNOWN_TRANSACTION_STATE": 0,
		"RESERVED":                  1,
		"SUCCESS":                   2,
		"FAILURE":                   3,
		"REJECTED":                  4,
	}
)

func (x TransactionState) Enum() *TransactionState {
	p := new(TransactionState)
	*p = x
	return p
}

func (x TransactionState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionState) Descriptor() protoreflect.EnumDescriptor {
	return file_middleware_wallet_proto_enumTypes[2].Descriptor()
}

func (TransactionState) Type() protoreflect.EnumType {
	return &file_middleware_wallet_proto_enumTypes[2]
}

func (x TransactionState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionState.Descriptor instead.
func (TransactionState) EnumDescriptor() ([]byte, []int) {
	return file_middleware_wallet_proto_rawDescGZIP(), []int{2}
}

type Operation int32

const (
	Operation_UNKNOWN_OPERATION Operation = 0
	// Зачисление на кошелёк.
	Operation_DEBIT Operation = 1
	// Списание с кошелька.
	Operation_CREDIT Operation = 2
	// Перевод между кошельками.
	Operation_SWAP Operation = 3
)

// Enum value maps for Operation.
var (
	Operation_name = map[int32]string{
		0: "UNKNOWN_OPERATION",
		1: "DEBIT",
		2: "CREDIT",
		3: "SWAP",
	}
	Operation_value = map[string]int32{
		"UNKNOWN_OPERATION": 0,
		"DEBIT":             1,
		"CREDIT":            2,
		"SWAP":              3,
	}
)

func (x Operation) Enum() *Operation {
	p := new(Operation)
	*p = x
	return p
}

func (x Operation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Operation) Descriptor() protoreflect.EnumDescriptor {
	return file_middleware_wallet_proto_enumTypes[3].Descriptor()
}

func (Operation) Type() protoreflect.EnumType {
	return &file_middleware_wallet_proto_enumTypes[3]
}

func (x Operation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Operation.Descriptor instead.
func (Operation) EnumDescriptor() ([]byte, []int) {
	return file_middleware_wallet_proto_rawDescGZIP(), []int{3}
}

type InformationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        *string                `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3,oneof" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InformationRequest) Reset() {
	*x = InformationRequest{}
	mi := &file_middleware_wallet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InformationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InformationRequest) ProtoMessage() {}

func (x *InformationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_middleware_wallet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InformationRequest.ProtoReflect.Descriptor instead.
func (*InformationRequest) Descriptor() ([]byte, []int) {
	return file_middleware_wallet_proto_rawDescGZIP(), []int{0}
}

func (x *InformationRequest) GetUserId() string {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return ""
}

type InformationReply struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Balance        int64                  `protobuf:"varint,2,opt,name=balance,proto3" json:"balance,omitempty"`
	ReservedDebit  int64                  `protobuf:"varint,3,opt,name=reserved_debit,json=reservedDebit,proto3" json:"reserved_debit,omitempty"`
	ReservedCredit int64                  `protobuf:"varint,4,opt,name=reserved_credit,json=reservedCredit,proto3" json:"reserved_credit,omitempty"`
	Type           WalletType             `protobuf:"varint,14,opt,name=type,proto3,enum=wallet.v1.WalletType" json:"type,omitempty"`
	State          WalletState            `protobuf:"varint,15,opt,name=state,proto3,enum=wallet.v1.WalletState" json:"state,omitempty"`
	Transactions   int64                  `protobuf:"varint,16,opt,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InformationReply) Reset() {
	*x = InformationReply{}
	mi := &file_middleware_wallet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InformationReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InformationReply) ProtoMessage() {}

func (x *InformationReply) ProtoReflect() protoreflect.Message {
	mi := &file_middleware_wallet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InformationReply.ProtoReflect.Descriptor instead.
func (*InformationReply) Descriptor() ([]byte, []int) {
	return file_middleware_wallet_proto_rawDescGZIP(), []int{1}
}

func (x *InformationReply) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InformationReply) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *InformationReply) GetReservedDebit() int64 {
	if x != nil {
		return x.ReservedDebit
	}
	return 0
}

func (x *InformationReply) GetReservedCredit() int64 {
	if x != nil {
		return x.ReservedCredit
	}
	return 0
}

func (x *InformationReply) GetType() WalletType {
	if x != nil {
		return x.Type
	}
	return WalletType_UNKNOWN_TYPE
}

func (x *InformationReply) GetState() WalletState {
	if x != nil {
		return x.State
	}
	return WalletState_UNKNOWN_STATE
}

func (x *InformationReply) GetTransactions() int64 {
	if x != nil {
		return x.Transactions
	}
	return 0
}

type InformationReplyList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Replies       []*InformationReply    `protobuf:"bytes,1,rep,name=replies,proto3" json:"replies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InformationReplyList) Reset() {
	*x = InformationReplyList{}
	mi := &file_middleware_wallet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InformationReplyList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InformationReplyList) ProtoMessage() {}

func (x *InformationReplyList) ProtoReflect() protoreflect.Message {
	mi := &file_middleware_wallet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InformationReplyList.ProtoReflect.Descriptor instead.
func (*InformationReplyList) Descriptor() ([]byte, []int) {
	return file_middleware_wallet_proto_rawDescGZIP(), []int{2}
}

func (x *InformationReplyList) GetReplies() []*InformationReply {
	if x != nil {
		return x.Replies
	}
	return nil
}

// OperationRequest описывает зачисление или списание.
//
// idempotency_key обязателен: повтор запроса при обрыве связи не должен
// провести операцию дважды. Повторный вызов с тем же ключом возвращает
// результат первой операции, а не создаёт новую.
type OperationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IdempotencyKey string                 `protobuf:"bytes,1,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	// Сумма в минимальных единицах, строго положительная. Направление
	// задаётся методом, а не знаком суммы.
	Value   int64  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	// Кошелёк владельца. Пустое значение — кошелёк по умолчанию.
	WalletId      *string `protobuf:"bytes,4,opt,name=wallet_id,json=walletId,proto3,oneof" json:"wallet_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationRequest) Reset() {
	*x = OperationRequest{}
	mi := &file_middleware_wallet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationRequest) ProtoMessage() {}

func (x *OperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_middleware_wallet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationRequest.ProtoReflect.Descriptor instead.
func (*OperationRequest) Descriptor() ([]byte, []int) {
	return file_middleware_wallet_proto_rawDescGZIP(), []int{3}
}

func (x *OperationRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *OperationRequest) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *OperationRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *OperationRequest) GetWalletId() string {
	if x != nil && x.WalletId != nil {
		return *x.WalletId
	}
	return ""
}

type TransferRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IdempotencyKey string                 `protobuf:"bytes,1,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	SourceWalletId string                 `protobuf:"bytes,2,opt,name=source_wallet_id,json=sourceWalletId,proto3" json:"source_wallet_id,omitempty"`
	TargetWalletId string                 `protobuf:"bytes,3,opt,name=target_wallet_id,json=targetWalletId,proto3" json:"target_wallet_id,omitempty"`
	Value          int64                  `protobuf:"varint,4,opt,name=value,proto3" json:"value,omitempty"`
	Message        string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TransferRequest) Reset() {
	*x = TransferRequest{}
	mi := &file_middleware_wallet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferRequest) ProtoMessage() {}

func (x *TransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_middleware_wallet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferRequest.ProtoReflect.Descriptor instead.
func (*TransferRequest) Descriptor() ([]byte, []int) {
	return file_middleware_wallet_proto_rawDescGZIP(), []int{4}
}

func (x *TransferRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *TransferRequest) GetSourceWalletId() string {
	if x != nil {
		return x.SourceWalletId
	}
	return ""
}

func (x *TransferRequest) GetTargetWalletId() string {
	if x != nil {
		return x.TargetWalletId
	}
	return ""
}

func (x *TransferRequest) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *TransferRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type TransactionReply struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	WalletId       string                 `protobuf:"bytes,2,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	SourceWalletId *string                `protobuf:"bytes,3,opt,name=source_wallet_id,json=sourceWalletId,proto3,oneof" json:"source_wallet_id,omitempty"`
	Operation      Operation              `protobuf:"varint,4,opt,name=operation,proto3,enum=wallet.v1.Operation" json:"operation,omitempty"`
	State          TransactionState       `protobuf:"varint,5,opt,name=state,proto3,enum=wallet.v1.TransactionState" json:"state,omitempty"`
	Value          int64                  `protobuf:"varint,6,opt,name=value,proto3" json:"value,omitempty"`
	Balance        int64                  `protobuf:"varint,7,opt,name=balance,proto3" json:"balance,omitempty"`
	Message        string                 `protobuf:"bytes,8,opt,name=message,proto3" json:"message,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TransactionReply) Reset() {
	*x = TransactionReply{}
	mi := &file_middleware_wallet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionReply) ProtoMessage() {}

func (x *TransactionReply) ProtoReflect() protoreflect.Message {
	mi := &file_middleware_wallet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionReply.ProtoReflect.Descriptor instead.
func (*TransactionReply) Descriptor() ([]byte, []int) {
	return file_middleware_wallet_proto_rawDescGZIP(), []int{5}
}

func (x *TransactionReply) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TransactionReply) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *TransactionReply) GetSourceWalletId() string {
	if x != nil && x.SourceWalletId != nil {
		return *x.SourceWalletId
	}
	return ""
}

func (x *TransactionReply) GetOperation() Operation {
	if x != nil {
		return x.Operation
	}
	return Operation_UNKNOWN_OPERATION
}

func (x *TransactionReply) GetState() TransactionState {
	if x != nil {
		return x.State
	}
	return TransactionState_UNKNOWN_TRANSACTION_STATE
}

func (x *TransactionReply) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *TransactionReply) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *TransactionReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TransactionReply) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type HistoryRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	WalletId *string                `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3,oneof" json:"wallet_id,omitempty"`
	// Ограничение выборки; ноль означает значение по умолчанию.
	Limit int32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	// Курсор: время создания последней полученной транзакции.
	Before        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=before,proto3,oneof" json:"before,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryRequest) Reset() {
	*x = HistoryRequest{}
	mi := &file_middleware_wallet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryRequest) ProtoMessage() {}

func (x *HistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_middleware_wallet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryRequest.ProtoReflect.Descriptor instead.
func (*HistoryRequest) Descriptor() ([]byte, []int) {
	return file_middleware_wallet_proto_rawDescGZIP(), []int{6}
}

func (x *HistoryRequest) GetWalletId() string {
	if x != nil && x.WalletId != nil {
		return *x.WalletId
	}
	return ""
}

func (x *HistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *HistoryRequest) GetBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.Before
	}
	return nil
}

type HistoryReply struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Transactions []*TransactionReply    `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	// Курсор для следующей страницы; пусто, если больше ничего нет.
	NextBefore    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=next_before,json=nextBefore,proto3,oneof" json:"next_before,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryReply) Reset() {
	*x = HistoryReply{}
	mi := &file_middleware_wallet_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryReply) ProtoMessage() {}

func (x *HistoryReply) ProtoReflect() protoreflect.Message {
	mi := &file_middleware_wallet_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryReply.ProtoReflect.Descriptor instead.
func (*HistoryReply) Descriptor() ([]byte, []int) {
	return file_middleware_wallet_proto_rawDescGZIP(), []int{7}
}

func (x *HistoryReply) GetTransactions() []*TransactionReply {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *HistoryReply) GetNextBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.NextBefore
	}
	return nil
}

type ChangeStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletId      string                 `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	State         WalletState            `protobuf:"varint,2,opt,name=state,proto3,enum=wallet.v1.WalletState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeStateRequest) Reset() {
	*x = ChangeStateRequest{}
	mi := &file_middleware_wallet_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeStateRequest) ProtoMessage() {}

func (x *ChangeStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_middleware_wallet_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeStateRequest.ProtoReflect.Descriptor instead.
func (*ChangeStateRequest) Descriptor() ([]byte, []int) {
	return file_middleware_wallet_proto_rawDescGZIP(), []int{8}
}

func (x *ChangeStateRequest) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *ChangeStateRequest) GetState() WalletState {
	if x != nil {
		return x.State
	}
	return WalletState_UNKNOWN_STATE
}

var File_middleware_wallet_proto protoreflect.FileDescriptor

const file_middleware_wallet_proto_rawDesc = "" +
	"\n" +
	"\x17middleware/wallet.proto\x12\twallet.v1\x1a\x1fgoogle/protobuf/timestamp.proto\">\n" +
	"\x12InformationRequest\x12\x1c\n" +
	"\auser_id\x18\x01 \x01(\tH\x00R\x06userId\x88\x01\x01B\n" +
	"\n" +
	"\b_user_id\"\xbf\x02\n" +
	"\x10InformationReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\abalance\x18\x02 \x01(\x03R\abalance\x12%\n" +
	"\x0ereserved_debit\x18\x03 \x01(\x03R\rreservedDebit\x12'\n" +
	"\x0freserved_credit\x18\x04 \x01(\x03R\x0ereservedCredit\x12)\n" +
	"\x04type\x18\x0e \x01(\x0e2\x15.wallet.v1.WalletTypeR\x04type\x12,\n" +
	"\x05state\x18\x0f \x01(\x0e2\x16.wallet.v1.WalletStateR\x05state\x12\"\n" +
	"\ftransactions\x18\x10 \x01(\x03R\ftransactionsJ\x04\b\x05\x10\x06J\x04\b\x06\x10\aJ\x04\b\a\x10\bJ\x04\b\b\x10\tJ\x04\b\t\x10\n" +
	"J\x04\b\n" +
	"\x10\vJ\x04\b\v\x10\fJ\x04\b\f\x10\rJ\x04\b\r\x10\x0e\"M\n" +
	"\x14InformationReplyList\x125\n" +
	"\areplies\x18\x01 \x03(\v2\x1b.wallet.v1.InformationReplyR\areplies\"\x9b\x01\n" +
	"\x10OperationRequest\x12'\n" +
	"\x0fidempotency_key\x18\x01 \x01(\tR\x0eidempotencyKey\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12 \n" +
	"\twallet_id\x18\x04 \x01(\tH\x00R\bwalletId\x88\x01\x01B\f\n" +
	"\n" +
	"_wallet_id\"\xbe\x01\n" +
	"\x0fTransferRequest\x12'\n" +
	"\x0fidempotency_key\x18\x01 \x01(\tR\x0eidempotencyKey\x12(\n" +
	"\x10source_wallet_id\x18\x02 \x01(\tR\x0esourceWalletId\x12(\n" +
	"\x10target_wallet_id\x18\x03 \x01(\tR\x0etargetWalletId\x12\x14\n" +
	"\x05value\x18\x04 \x01(\x03R\x05value\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\"\xef\x02\n" +
	"\x10TransactionReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\twallet_id\x18\x02 \x01(\tR\bwalletId\x12-\n" +
	"\x10source_wallet_id\x18\x03 \x01(\tH\x00R\x0esourceWalletId\x88\x01\x01\x122\n" +
	"\toperation\x18\x04 \x01(\x0e2\x14.wallet.v1.OperationR\toperation\x121\n" +
	"\x05state\x18\x05 \x01(\x0e2\x1b.wallet.v1.TransactionStateR\x05state\x12\x14\n" +
	"\x05value\x18\x06 \x01(\x03R\x05value\x12\x18\n" +
	"\abalance\x18\a \x01(\x03R\abalance\x12\x18\n" +
	"\amessage\x18\b \x01(\tR\amessage\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtB\x13\n" +
	"\x11_source_wallet_id\"\x9a\x01\n" +
	"\x0eHistoryRequest\x12 \n" +
	"\twallet_id\x18\x01 \x01(\tH\x00R\bwalletId\x88\x01\x01\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x127\n" +
	"\x06before\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\x06before\x88\x01\x01B\f\n" +
	"\n" +
	"_wallet_idB\t\n" +
	"\a_before\"\xa1\x01\n" +
	"\fHistoryReply\x12?\n" +
	"\ftransactions\x18\x01 \x03(\v2\x1b.wallet.v1.TransactionReplyR\ftransactions\x12@\n" +
	"\vnext_before\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\n" +
	"nextBefore\x88\x01\x01B\x0e\n" +
	"\f_next_before\"_\n" +
	"\x12ChangeStateRequest\x12\x1b\n" +
	"\twallet_id\x18\x01 \x01(\tR\bwalletId\x12,\n" +
	"\x05state\x18\x02 \x01(\x0e2\x16.wallet.v1.WalletStateR\x05state*4\n" +
	"\n" +
	"WalletType\x12\x10\n" +
	"\fUNKNOWN_TYPE\x10\x00\x12\b\n" +
	"\x04USER\x10\x01\x12\n" +
	"\n" +
	"\x06COMMON\x10\x02*R\n" +
	"\vWalletState\x12\x11\n" +
	"\rUNKNOWN_STATE\x10\x00\x12\n" +
	"\n" +
	"\x06ACTIVE\x10\x01\x12\v\n" +
	"\aBLOCKED\x10\x02\x12\v\n" +
	"\aDELETED\x10\x03\x12\n" +
	"\n" +
	"\x06CLOSED\x10\x04*g\n" +
	"\x10TransactionState\x12\x1d\n" +
	"\x19UNKNOWN_TRANSACTION_STATE\x10\x00\x12\f\n" +
	"\bRESERVED\x10\x01\x12\v\n" +
	"\aSUCCESS\x10\x02\x12\v\n" +
	"\aFAILURE\x10\x03\x12\f\n" +
	"\bREJECTED\x10\x04*C\n" +
	"\tOperation\x12\x15\n" +
	"\x11UNKNOWN_OPERATION\x10\x00\x12\t\n" +
	"\x05DEBIT\x10\x01\x12\n" +
	"\n" +
	"\x06CREDIT\x10\x02\x12\b\n" +
	"\x04SWAP\x10\x032\xae\x03\n" +
	"\aService\x12M\n" +
	"\vInformation\x12\x1d.wallet.v1.InformationRequest\x1a\x1f.wallet.v1.InformationReplyList\x12A\n" +
	"\x05Debit\x12\x1b.wallet.v1.OperationRequest\x1a\x1b.wallet.v1.TransactionReply\x12B\n" +
	"\x06Credit\x12\x1b.wallet.v1.OperationRequest\x1a\x1b.wallet.v1.TransactionReply\x12C\n" +
	"\bTransfer\x12\x1a.wallet.v1.TransferRequest\x1a\x1b.wallet.v1.TransactionReply\x12=\n" +
	"\aHistory\x12\x19.wallet.v1.HistoryRequest\x1a\x17.wallet.v1.HistoryReply\x12I\n" +
	"\vChangeState\x12\x1d.wallet.v1.ChangeStateRequest\x1a\x1b.wallet.v1.InformationReplyB\x16Z\x14middleware/wallet/v1b\x06proto3"

var (
	file_middleware_wallet_proto_rawDescOnce sync.Once
	file_middleware_wallet_proto_rawDescData []byte
)

func file_middleware_wallet_proto_rawDescGZIP() []byte {
	file_middleware_wallet_proto_rawDescOnce.Do(func() {
		file_middleware_wallet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_middleware_wallet_proto_rawDesc), len(file_middleware_wallet_proto_rawDesc)))
	})
	return file_middleware_wallet_proto_rawDescData
}

var file_middleware_wallet_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_middleware_wallet_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_middleware_wallet_proto_goTypes = []any{
	(WalletType)(0),               // 0: wallet.v1.WalletType
	(WalletState)(0),              // 1: wallet.v1.WalletState
	(TransactionState)(0),         // 2: wallet.v1.TransactionState
	(Operation)(0),                // 3: wallet.v1.Operation
	(*InformationRequest)(nil),    // 4: wallet.v1.InformationRequest
	(*InformationReply)(nil),      // 5: wallet.v1.InformationReply
	(*InformationReplyList)(nil),  // 6: wallet.v1.InformationReplyList
	(*OperationRequest)(nil),      // 7: wallet.v1.OperationRequest
	(*TransferRequest)(nil),       // 8: wallet.v1.TransferRequest
	(*TransactionReply)(nil),      // 9: wallet.v1.TransactionReply
	(*HistoryRequest)(nil),        // 10: wallet.v1.HistoryRequest
	(*HistoryReply)(nil),          // 11: wallet.v1.HistoryReply
	(*ChangeStateRequest)(nil),    // 12: wallet.v1.ChangeStateRequest
	(*timestamppb.Timestamp)(nil), // 13: google.protobuf.Timestamp
}
var file_middleware_wallet_proto_depIdxs = []int32{
	0,  // 0: wallet.v1.InformationReply.type:type_name -> wallet.v1.WalletType
	1,  // 1: wallet.v1.InformationReply.state:type_name -> wallet.v1.WalletState
	5,  // 2: wallet.v1.InformationReplyList.replies:type_name -> wallet.v1.InformationReply
	3,  // 3: wallet.v1.TransactionReply.operation:type_name -> wallet.v1.Operation
	2,  // 4: wallet.v1.TransactionReply.state:type_name -> wallet.v1.TransactionState
	13, // 5: wallet.v1.TransactionReply.created_at:type_name -> google.protobuf.Timestamp
	13, // 6: wallet.v1.HistoryRequest.before:type_name -> google.protobuf.Timestamp
	9,  // 7: wallet.v1.HistoryReply.transactions:type_name -> wallet.v1.TransactionReply
	13, // 8: wallet.v1.HistoryReply.next_before:type_name -> google.protobuf.Timestamp
	1,  // 9: wallet.v1.ChangeStateRequest.state:type_name -> wallet.v1.WalletState
	4,  // 10: wallet.v1.Service.Information:input_type -> wallet.v1.InformationRequest
	7,  // 11: wallet.v1.Service.Debit:input_type -> wallet.v1.OperationRequest
	7,  // 12: wallet.v1.Service.Credit:input_type -> wallet.v1.OperationRequest
	8,  // 13: wallet.v1.Service.Transfer:input_type -> wallet.v1.TransferRequest
	10, // 14: wallet.v1.Service.History:input_type -> wallet.v1.HistoryRequest
	12, // 15: wallet.v1.Service.ChangeState:input_type -> wallet.v1.ChangeStateRequest
	6,  // 16: wallet.v1.Service.Information:output_type -> wallet.v1.InformationReplyList
	9,  // 17: wallet.v1.Service.Debit:output_type -> wallet.v1.TransactionReply
	9,  // 18: wallet.v1.Service.Credit:output_type -> wallet.v1.TransactionReply
	9,  // 19: wallet.v1.Service.Transfer:output_type -> wallet.v1.TransactionReply
	11, // 20: wallet.v1.Service.History:output_type -> wallet.v1.HistoryReply
	5,  // 21: wallet.v1.Service.ChangeState:output_type -> wallet.v1.InformationReply
	16, // [16:22] is the sub-list for method output_type
	10, // [10:16] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_middleware_wallet_proto_init() }
func file_middleware_wallet_proto_init() {
	if File_middleware_wallet_proto != nil {
		return
	}
	file_middleware_wallet_proto_msgTypes[0].OneofWrappers = []any{}
	file_middleware_wallet_proto_msgTypes[3].OneofWrappers = []any{}
	file_middleware_wallet_proto_msgTypes[5].OneofWrappers = []any{}
	file_middleware_wallet_proto_msgTypes[6].OneofWrappers = []any{}
	file_middleware_wallet_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_middleware_wallet_proto_rawDesc), len(file_middleware_wallet_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_middleware_wallet_proto_goTypes,
		DependencyIndexes: file_middleware_wallet_proto_depIdxs,
		EnumInfos:         file_middleware_wallet_proto_enumTypes,
		MessageInfos:      file_middleware_wallet_proto_msgTypes,
	}.Build()
	File_middleware_wallet_proto = out.File
	file_middleware_wallet_proto_goTypes = nil
	file_middleware_wallet_proto_depIdxs = nil
}
